devMode = false
autoSwitchLanguage = true
autoDownloadVMTranslationPack = false
checkModPackTranslationUpdate = true
autoLoadExtraTranslationPack = true
extraPackName = "VM Language Override"
extraPackIndex = "TOP_OF_CFPA"
extraPackCustomIndex = 0
i18nUpdateModCheck = true
vaultPatcherCheck = false
